name: Python package

on:
  push:
    paths:
      - ".github/workflows/package.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # python-version: ["3.9", "3.10", "3.11"]
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install automake
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install poetry
          poetry install
          pip install stickytape
          make dist_script
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: derive-linux
          path: dist/
